config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'customers#index'
  resources :customers do
    resources :orders, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apprearance.rb
class Apprearance < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :sex

  has_many :orders, dependent: :destroy
  belongs_to :user

  validates :name, presence: true, length: { maximum: 20, message: 'は20文字以内で入力してください' }
  with_options format: { with: /\A\d{10,11}\z/, allow_blank: true, message: 'はハイフンなしで入力してください' } do
    validates :tell1
    validates :tell2
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, touch: true

  with_options presence: true do
    validates :date
    validates :people, numericality: { only_integer: true, message: 'は半角数字で入力してください' }
    validates :pay, numericality: { only_integer: true, message: 'は半角数字で入力してください' }
  end
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' },
    { id: 3, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :customer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers

  with_options presence: true do
    validates :name
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください' }
  end

  # 物理削除の代わりにユーザーの`deleted_at`をタイムスタンプで更新
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ユーザーのアカウントが有効であることを確認
  def active_for_authentication?
    super && !deleted_at
  end

  # 削除したユーザーにカスタムメッセージを追加します
  def inactive_message
    !deleted_at ? super : :deleted_account
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :search_customer, only: [:index, :search]
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.eager_load(:user, :orders).where(user_id: current_user.id).order(updated_at: 'DESC')
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.valid?
      @customer.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
    @orders = Order.where(customer_id: @customer.id).order('date DESC')
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to root_path
  end

  def search
    @results = @keyword.result.order('updated_at DESC')
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :name_kana, :sex_id,
                                     :tell1, :tell2, :email, :address, :memo, :appearance).merge(user_id: current_user.id)
  end

  def search_customer
    @sex = Sex.all
    if !params[:q].nil?
      params[:q]['name_or_name_kana_or_tell1_or_memo_or_appearance_cont_all'] =
        params[:q]['name_or_name_kana_or_tell1_or_memo_or_appearance_cont_all'].split(/[\p{blank}\s]+/)
      @keyword = Customer.includes(:orders).ransack(params[:q])
    else
      @keyword = Customer.includes(:orders).ransack(params[:q])
    end
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:edit, :update, :destroy]

  def new
    @customer = Customer.new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.valid?
      @order.save
      redirect_to customer_path(@order.customer.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to customer_path(@order.customer.id)
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to customer_path(@order.customer.id)
  end

  private

  def order_params
    params.require(:order).permit(:date, :people, :table, :drink, :food, :pay,
                                  :order_memo).merge(customer_id: params[:customer_id])
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # DELETE /resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    yield resource if block_given?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(current_user.id)
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/edit.html.erb
<div class="container mb-5 mt-2">
  <h1>お客様編集</h1>

  <%= render 'shared/form' %>
</div>

app/views/customers/index.html.erb
<div class="container mb-5">
  <div class="row col-10 mt-2">
    <h2>お客様一覧</h2>
  </div>

  <div class="row pl-3 pr-3 d-flex justify-content-between">
    <div>
      <%= render 'shared/search' %>
    </div>
    <div>
      <a href="customers/new" class="btn btn-info pull-right">お客様新規登録</a>
    </div>
  </div>

  <%# お客様一覧 %>
  <div class="mt-2">
    <% if @customers.present? %>
      <% @customers.each do |customer| %>
      <% wday = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']%>
        <%= link_to customer_path(customer.id), class: 'link_black' do %>
          <button class="border p-1 pl-2 mt-3 rounded-lg col-12 text-left">
            <div>
              <%= customer.name %>&emsp;
              <%= customer.name_kana %>
            </div>
            <div>
              &emsp;<%= customer.memo %>
              &emsp;<%= customer.appearance %>
            </div>
            <div>
              <% if customer.orders.present? %>
                &emsp;最終来店日：<%= customer.orders.last.date %> <%= wday[customer.orders.last.date.wday] %>
              <% else %>
                &emsp;来店データはありません
              <% end %>
            </div>
          </button>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/customers/new.html.erb
<div class="container mb-5 mt-2">
  <h2>顧客情報登録</h2>

  <%= render 'shared/form' %>
  
</div>

app/views/customers/search.html.erb
<div class="container mb-5">
  <div class="row col-10 mt-2">
    <h2>検索結果</h2>
  </div>

  <div class="row pl-3 pr-3 d-flex justify-content-between">
    <div>
      <%# 検索窓 %>
      <%= render 'shared/search' %>
    </div>
    <div>
      <a href="/customers/new" class="btn btn-info pull-right">お客様新規登録</a>
    </div>
  </div>

  <div>
  <%# 検索結果表示 %>
  <% if @results.present? %>
      <% @results.each do |customer| %>
        <% wday = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']%>
        <%= link_to customer_path(customer.id), class: 'link_black' do %>
          <button class="border p-1 pl-2 mt-2 rounded-lg col-12 text-left">
            <div>
              <%= customer.name %>&emsp;
              <%= customer.name_kana %>
            </div>
            <div>
              &emsp;<%= customer.memo %>
              &emsp;<%= customer.appearance %>
            </div>
            <div>
              <% if customer.orders.present? %>
                &emsp;最終来店日：<%= customer.orders.last.date %> <%= wday[customer.orders.last.date.wday] %>
              <% else %>
                &emsp;来店データはありません
              <% end %>
            </div>
          </button>
        <% end %>
      <% end %>
    <% else %>
      <div>***条件に当てはまるお客様はありません***</div>
    <% end %>
  </div>

  <a href="/" class="btn btn-info btn-sm mt-3 mb-3" role="button" methodo="get">トップページ</a>
</div>

app/views/customers/show.html.erb
<div class="container mb-5">
  <%# お客様詳細情報 %>
  <div class="row mt-2">
    <h1><%= @customer.name%>  様</h1>
  </div>
  <div class="row pl-3 pr-3 d-flex justify-content-between">
    <div class="text-left">
      <a href="/" class="btn btn-info btn-sm" role="button" methodo="get">トップページ</a>
    </div>
    <div class="text-right">
      <%= link_to  new_customer_order_path(@customer.id), class: 'link_white' do %>
        <button class="btn btn-info btn-sm mr-2">オーダー情報入力</button>
      <% end %>
      <%= link_to  edit_customer_path(@customer.id), class: 'link_white' do %>
        <button class="btn btn-primary btn-sm mr-2">お客様編集</button>
      <% end %>
      <%= link_to customer_path(@customer.id), method: :delete, data: { confirm: "お客様を削除しますか？" }, class: 'link_white' do %>
        <button class="btn btn-danger btn-sm">お客様削除</button>
      <% end %>
    </div>
  </div>

    <table class="table table-striped border mt-4">
      <tr>
        <th style="width:30vw;">お名前</th>
        <td><%= @customer.name %>  様</td>
      </tr>
      <tr>
        <th>お名前(フリガナ)</th>
        <td><%= @customer.name_kana %>  様</td>
      </tr>
      <tr>
        <th>性別</th>
        <td><%= @customer.sex.name %></td>
      </tr>
      <tr>
        <th>電話番号-1</th>
        <td><%= @customer.tell1 %></td>
      </tr>
      <tr>
        <th>電話番号-2</th>
        <td><%= @customer.tell2 %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>来店回数</th>
        <td><%= @customer.orders.count %></td>
      </tr>
      <tr>
        <th>メモ</th>
        <td><%= @customer.memo %></td>
      </tr>
      <tr>
        <th>外見的特徴</th>
        <td><%= @customer.appearance %></td>
      </tr>
    </table>

      <div class="row mt-4 mb-3">
        <div class="col-sm-5 text-center">
          <h3 class="border rounded-lg border-info p-2">オーダー一覧</h3>
        </div>
      </div>

  <%# オーダー一覧 %>
  <div class="col mb-5">
    <% if @orders.present? %>
      <% @orders.each do |order| %>
      <% wday = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']%>
        <div class="col border rounded mt-3 mb-2 bg-light">
          <div class="row d-flex justify-content-end pr-3">
            <%= link_to edit_customer_order_path(@customer.id, order.id), class: 'link_white' do %>
              <button class="btn btn-primary btn-sm">編集</button>
            <% end %>
            <%= link_to customer_order_path(@customer.id, order.id), class: 'link_white', method: :delete, data: { confirm: 'オーダーを削除しますか？' } do %>
              <button class="btn btn-danger btn-sm ml-2">削除</button>
            <% end %>
          </div>

          <table class="table table-sm border rounded-lg bg-white">
            <tbody>
              <tr>
                <th scope="row" style="width:30vw;">来店日</th>
                <td><%= order.date %> <%= wday[order.date.wday] %></td>
              </tr>
              <tr>
                <th scope="row">人数</th>
                <td><%= order.people %> 名</td>
              </tr>
              <tr>
                <th scope="row">テーブル番号</th>
                <td><%= order.table %></td>
              </tr>
              <tr>
                <th scope="row">ドリンクオーダー</th>
                <td><%= order.drink %></td>
              </tr>
              <tr>
                <th scope="row">フードオーダー</th>
                <td><%= order.food %></td>
              </tr>
              <tr>
                <th scope="row">会計金額</th>
                <td><%= order.pay.to_s(:delimited) %>円</td>
              </tr>
              <tr>
                <th scope="row">memo</th>
                <td><%= order.order_memo %></td>
              </tr>
            </tbody>
          </table>
        </div>

      <% end %>
    <%# オーダー情報が無い場合 %>
    <% else %>
      <p class="h3 text-center">*** オーダー情報はありません ***</p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerInfo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@800&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar sticky-top bg-info text-white">
      <h1><%= link_to 'Cliente', root_path, class: "app-name" %></h1>
      <div class="navbar-text navbar-right h4">
        <% if user_signed_in? %>
          <%= current_user.name %>
          <%= link_to edit_user_path(current_user.id) do %>
            <button type="button" class="btn btn-light btn-sm border ml-4">ユーザー編集</button>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'link_white' do %>
            <button type="button" class="btn btn-outline-danger btn-sm">ログアウト</button>
          <% end %>
        <% else %>
          <%= link_to new_user_registration_path, class: 'link_white' do %>
            <button type="button" class="btn btn-outline-light btn-sm mr-2">ユーザー登録</button>
          <% end %>
          <%= link_to  new_user_session_path, class: 'link_white' do %>
            <button type="button" class="btn btn-primary btn-sm mr-3">ログイン</button>
          <% end %>
        <% end %>
      </div>
    </nav>

    <%= yield %>

    <footer class="footer fixed-bottom bg-info">
      <p class="text-white pl-5 pt-1">Cliente costomer-info.</p>
    </footer>

  </body>
</html>

app/views/orders/edit.html.erb
<div class="container mb-5 mt-2">
  <h2>オーダー編集</h2>

  <%= form_with model: [@customer, @order], url: customer_order_path, method: :patch, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

    <div class="mt-3">
      <%= f.label '来店日' %> <span class="badge badge-danger">必須</span>
    </div>
    <div class="col">
      <%= f.date_field :date %>
    </div>

    <div class="mt-2">
      <label>来店人数</label> <span class="badge badge-danger">必須</span>
    </div>
    <div class="col">
      <%= f.text_field :people, class: "text-right", placeholder:"例）3" %> 名
    </div>

    <div class="mt-2">
      <label>テーブル番号</label>
    </div>
    <div class="col">
      <%= f.text_field :table, placeholder:"例）A5" %>
    </div>

    <div class="mt-2">
      <label>ドリンクオーダー</label>
    </div>
    <div class="col">
      <%= f.text_area :drink, placeholder:"例）ビール4", class: "text_area" %>
    </div>

    <div class="mt-2">
      <label>フードオーダー</label>
    </div>
    <div class="col">
      <%= f.text_area :food, placeholder:"例）ポモドーロ1", class: "text_area" %>
    </div>

    <div class="mt-2 w-4">
      <label>支払い金額</label> <span class="badge badge-danger">必須</span>
    </div>
    <div class="col">
      <%= f.text_field :pay, class: "text-right", placeholder:"例）12000" %> 円
    </div>

    <div class="mt-2">
      <label>メモ</label>
    </div>
    <div class="col">
      <%= f.text_area :order_memo %>
    </div>

    <div class="sell-btn-contents mt-3 ml-3">
      <%= f.submit "登録する" %>
      <%= link_to 'もどる', customer_path(params[:customer_id]) %>
    </div>

  <% end %>
</div>

app/views/orders/new.html.erb
<div class="container mb-5 mt-2">
  <h2>オーダー入力</h2>

  <%= form_with model: [@customer, @order], url: customer_orders_path, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="mt-3">
      <label for="order_date">来店日</label> <span class="badge badge-danger">必須</span>
    </div>
    <div class="col">
      <%= f.date_field :date %>
    </div>

    <div class="mt-2">
      <label for="order_people">来店人数</label> <span class="badge badge-danger">必須</span>
    </div>
    <div class="col">
      <%= f.text_field :people, class: "text-right", placeholder:"例）3" %> 名
    </div>

    <div class="mt-2">
      <label for="order_table">テーブル番号</label>
    </div>
    <div class="col">
      <%= f.text_field :table, placeholder:"例）A5" %>
    </div>

    <div class="mt-2">
      <label for="order_drink">ドリンクオーダー</label>
    </div>
    <div class="col">
      <%= f.text_area :drink, placeholder:"例）ビール4", class: "text_area" %>
    </div>

    <div class="mt-2">
      <label for="order_food">フードオーダー</label>
    </div>
    <div class="col">
      <%= f.text_area :food, placeholder:"例）ポモドーロ1", class: "text_area" %>
    </div>

    <div class="mt-2 w-4">
      <label for="order_pay">支払い金額</label> <span class="badge badge-danger">必須</span>
    </div>
    <div class="col">
      <%= f.text_field :pay, class: "text-right", placeholder:"例）12000" %> 円
    </div>

    <div class="mt-2">
      <label for="order_order_memo">メモ</label>
    </div>
    <div class="col">
      <%= f.text_area :order_memo %>
    </div>

    <div class="sell-btn-contents mt-3 ml-3">
      <%= f.submit "登録する" %>
      <%= link_to 'もどる', customer_path(params[:customer_id]) %>
    </div>

  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_form.html.erb
<%# 入力フォーム %>
<%= form_with model: @customer, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

    <div>
      <label for="customer_name">お名前</label> <span class="badge badge-danger">必須</span>
    </div>
    <div>
      <%= f.text_field :name, autofocus: true, placeholder:"例) 山田 太郎" %>
    </div>

    <div>
      <label for="customer_name_kana" class="mt-2">お名前カナ</label>
    </div>
    <div>
      <%= f.text_field :name_kana, placeholder:"例) ヤマダ タロウ", pattern: "(?=.*?[\u30A1-\u30FC])[\u30A1-\u30FC\s|　]*" %>
      <%# 全角カタカナ、半角・全角スペースのみ %>
    </div>

    <div class="form-group">
      <div>
        <label for="item-category" class="control-label mt-2">性別</label>
      </div>
      <div>
        <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
    </div>

    <div>
      <label for="customer_tell1">電話番号-1</label>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :tell1, class: "form", placeholder:"例）09012345678",maxlength:"11"%>
    </div>

    <div>
      <label for="customer_tell2" class="form-text">電話番号-2</label>
    </div>
    <div>
      <%= f.text_field :tell2, class: "form", placeholder:"例）09012345678",maxlength:"11"%>
    </div>

    <div>
      <label for="customer_email" class="form-text">メールアドレス</label>
    </div>
    <div>
      <%= f.email_field :email, class: "memo", placeholder:"PC・携帯どちらでも可" %>
    </div>

    <div>
      <label for="customer_address" class="form-text">住所</label>
    </div>
    <div >
      <%= f.text_area :address, class: "memo", placeholder:"例) 神奈川県鎌倉市材木座1-1" %>
    </div>

    <div>
      <label for="customer_memo" class="form-text">メモ</label>
    </div>
    <div>
      <%= f.text_area :memo, class: "text_area", placeholder:"" %>
    </div>

    <div>
      <label for="customer_appearance" class="form-text">外見情報</label>
    </div>
    <div >
      <%= f.text_area :appearance, class: "text_area", placeholder:"" %>
    </div>

    <div class="md-5">
      <%= f.submit "登録する" %>
      <a href="/">もどる</a>
    </div>

<% end %>

app/views/shared/_search.html.erb
<%# 検索窓 %>
    <div>
      <%= search_form_for @keyword, url: search_customers_path do |f| %>
        <%= f.search_field :name_or_name_kana_or_tell1_or_memo_or_appearance_cont_all, required: true, placeholder: "お客様検索", class: "search-input" %>
        
        <%= f.label :sex_id_eq, '　性別' %>
        <%= f.collection_select :sex_id_eq, @sex, :id, :name, :include_blank => '指定なし' %>
        <button type="submit", class="btn btn-primary btn-sm">検索</button>
      <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container mb-5 mt-2">
  <h2><%= current_user.name %> 様</h2>

  <%= form_with model: current_user, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

  <div>
    <%= f.label '名前' %> <span class="badge badge-danger">必須</span>
  </div>
  <div>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="mt-2">
    <%= f.label 'メールアドレス' %> <span class="badge badge-danger">必須</span>
  </div>
  <div>
    <%= f.email_field :email, autocomplete: "email" %>
  </div>


  <div class="mt-2">
    <%= f.label 'パスワード' %> <span class="badge badge-danger">必須</span> <i>(変更する場合は新たなパスワードを入力してください。)</i><br />
    <%= f.password_field :password, autocomplete: "new-password", placeholder:"6文字以上半角英数" %>
  </div>

  <div class="mt-2">
    <%= f.label 'パスワード確認' %> <span class="badge badge-danger">必須</span> <i>(上記と同じパスワードを入力してください。)</i><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder:"上記と同じもの" %>
  </div>

  <div class="mt-2">
    <%= f.submit "更新" %>
    <a href="/" class="mt-3">もどる</a>
  </div>
  <% end %>

  <div>
    <%= link_to user_registration_path(current_user), method: :delete, class: 'link_white', data: { confirm: "ユーザーを削除しますか？" } do %>
      <bottom type="button" class="btn btn-outline-danger btn-sm mt-3">ユーザー削除</bottom>
    <% end %>
  </div>
</div>